name: Example key vault flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "iot-secrets"
        secrets: 'REACT-APP-IOT-WEB-API-SCOPE, REACT-APP-IOT-WEB-API,REACT-APP-CLIENT-ID,REACT-APP-TENANT,REACT-APP-USER-FLOW-RESET,REACT-APP-USER-FLOW-EDIT,REACT-APP-USER-FLOW-SIGN,REACT-APP-HUB-NAME,REACT-APP-SIGNALR-URL,REACT-APP-API-IOT-MSG-URL,REACT-APP-API-URL'
      id: secretsAction
    - run: |
        echo "#${{ steps.secretsAction.outputs.REACT-APP-IOT-WEB-API-SCOPE }}#"
