name: Example key vault flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "iot-secrets"
        secrets: 'REACT*'
      id: secretsAction
    - run: |
        echo "#${{ steps.secretsAction.outputs.REACT-APP-IOT-WEB-API-SCOPE }}#"
